export const BASE_URL = "http://138.197.170.239:8080/";
export const SOKET_URL = "http://138.197.170.239:8080/";

const api = {
    SOKET_URL: SOKET_URL,
    POST_S_LOGIN: BASE_URL + "sadmin",
    POST_LOGIN: BASE_URL + "login",
    RESET_PASSWORD: BASE_URL + "forget_password/reset-link",
    GET_COMPANY: BASE_URL + "company/list",
    GET_COMPANY_FILTER: BASE_URL + "company/filter/company_list",
    ADD_COMPANY: BASE_URL + "company/add",
    DELETE_COMPANY: BASE_URL + "company/delete",
    GET_PROPERTY_SADMIN: BASE_URL + "property/list",
    GET_PROPERTY_SADMIN_Filter: BASE_URL + "property/filter",
    GET_PROPERTY_Manager: BASE_URL + "property_manager/list",
    GET_PROPERTY_Manager_Filter: BASE_URL + "property_manager/filter",
    GET_APPLICANT: BASE_URL + "applicant/list",
    GET_APPLICANT_FILTER: BASE_URL + "applicant/getPropertyNameFilterValue",
    GET_LAYOUT: BASE_URL + "layout/all",
    ADD_LAYOUT: BASE_URL + "layout/add",
    DELETE_LAYOUT: BASE_URL + "layout/delete",
    PROPERTY_ADD: BASE_URL + "property/add",
    UPLOAD_DOC: BASE_URL + "property/upload-documents",
    DELETE_PROPERTY: BASE_URL + "property/delete",
    GET_LEADES_COMPANY: BASE_URL + "leads/getLeads",


    POST_CREATE_OTP: BASE_URL + "otp/create",
    POST_VERIFY_OTP: BASE_URL + "otp/verify",
    POST_VERIFY: BASE_URL + "user/verify",
    POST_REGISTERT: BASE_URL + "user",
    UPDATE_USER: BASE_URL + "user",
    GET_USER: BASE_URL + "user/profile",
    SOCIAL_LOGIN: BASE_URL + "user/social/login",
    CHANGE_PASSWOARD: BASE_URL + "user/password/change",
    GET_ANIMAL: BASE_URL + "animal",
    ADD_PET: BASE_URL + "pet",
    UPDATE_PET: BASE_URL + "pet",
    GET_PET: BASE_URL + "pet",
    UPLOAD_FILE: BASE_URL + "s3upload/image-upload",
    PET_SEL: BASE_URL + "sell",
    ADD_POST: BASE_URL + "post",
    GET_POST: BASE_URL + "post",
    GET_HOME_POST: BASE_URL + "post/home",
    SAVE_POST: BASE_URL + "savePost",
    GET_SAVE_POST: BASE_URL + "savePost",
    GET_SAVE_LIST: BASE_URL + "savePost/sell",
    POST_LIKE: BASE_URL + "like",
    GET_COMMENT: BASE_URL + "comment",
    GET_USERS: BASE_URL + "user/userList",
    FOLLOW: BASE_URL + "follow",
    GET_CHAT: BASE_URL + "chat",
    ACCEPT_CHAT: BASE_URL + "chat/accept",
    GET_INDIVIDUAL_CHAT: BASE_URL + "chat/individual",
    ADD_SUBSCRIPTION: BASE_URL + "transaction",
    // RESET_PASSWORD: BASE_URL + "user/resetPassword",
    GET_ACTIVITY: BASE_URL + "activity",
    BLOCK_POST: BASE_URL + "blockUser/block",
    GET_BLOCK: BASE_URL + "blockUser",
    UNBLOCK_USER: BASE_URL + "blockUser/unblock",
    GET_SONG: BASE_URL + "song",
    WEBVIEW: BASE_URL + "webview",
    DELETE_USER: BASE_URL + "user",
    GET_PRODUCT: BASE_URL + "subscription",
    PAYMENT: BASE_URL + "subscription/paymentSheet",
    PET_DELETE: BASE_URL + "pet",
    REPORT_USER: BASE_URL + "report",



};

export default api;
